In [1]:
import numpy as np
import pandas as pd

In [2]:
raw = pd.read_csv('1.02.+Multiple+linear+regression.csv')

In [3]:
raw.head(5)

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [35]:
x = raw.iloc[:, :-1].values
y = raw.iloc[:, -1].values

In [36]:
x

array([[1714,    1],
       [1664,    3],
       [1760,    3],
       [1685,    3],
       [1693,    2],
       [1670,    1],
       [1764,    2],
       [1764,    1],
       [1792,    2],
       [1850,    3],
       [1735,    3],
       [1775,    2],
       [1735,    1],
       [1712,    3],
       [1773,    2],
       [1872,    2],
       [1755,    3],
       [1674,    2],
       [1842,    3],
       [1786,    3],
       [1761,    3],
       [1722,    3],
       [1663,    3],
       [1687,    1],
       [1974,    1],
       [1826,    1],
       [1787,    1],
       [1821,    3],
       [2020,    1],
       [1794,    2],
       [1769,    1],
       [1934,    1],
       [1775,    1],
       [1855,    3],
       [1880,    2],
       [1849,    2],
       [1808,    3],
       [1954,    3],
       [1777,    3],
       [1831,    2],
       [1865,    3],
       [1850,    1],
       [1966,    3],
       [1702,    1],
       [1990,    1],
       [1925,    2],
       [1824,    2],
       [1956,

In [44]:
from sklearn.compose import ColumnTransformer

In [45]:
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import OneHotEncoder

In [46]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')

In [47]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [1])])

In [48]:
import numpy as np

In [49]:
N = np.array(ct.fit_transform(raw))

In [63]:
N

array([[1.00e+00, 0.00e+00, 0.00e+00, 1.71e+03, 2.40e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 1.66e+03, 2.52e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 1.76e+03, 2.54e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 1.68e+03, 2.74e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.69e+03, 2.83e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.67e+03, 2.91e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.76e+03, 3.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.76e+03, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.79e+03, 3.01e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 1.85e+03, 3.01e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 1.74e+03, 3.02e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.78e+03, 3.07e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, 1.74e+03, 3.08e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 1.71e+03, 3.08e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.77e+03, 3.12e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, 1.87e+03, 3.17e+00],
       [0.00e+00, 0.00e+00, 1.00e+00, 1.76e+03, 3.17e+00

In [64]:
from sklearn.model_selection import train_test_split

In [52]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [53]:
from sklearn.linear_model import LinearRegression

In [54]:
LR = LinearRegression()

In [55]:
MC = LR.fit(x_train,y_train)

In [56]:
MC

LinearRegression()

In [57]:
y_pred = LR.predict(x_test)

In [58]:
y_pred

array([3.43, 3.18, 3.24, 3.04, 3.21, 3.43, 3.14, 3.3 , 3.12, 3.32, 3.33,
       3.53, 3.34, 3.51, 3.43, 3.42, 3.32])

In [59]:
np.set_printoptions(precision = 2)

In [62]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3.43 3.6 ]
 [3.18 2.4 ]
 [3.24 3.47]
 [3.04 3.2 ]
 [3.21 3.08]
 [3.43 3.59]
 [3.14 3.02]
 [3.3  3.17]
 [3.12 2.83]
 [3.32 3.52]
 [3.33 3.37]
 [3.53 3.4 ]
 [3.34 3.31]
 [3.51 3.73]
 [3.43 3.47]
 [3.42 3.44]
 [3.32 3.29]]


array([3.43, 3.18, 3.24, 3.04, 3.21, 3.43, 3.14, 3.3 , 3.12, 3.32, 3.33,
       3.53, 3.34, 3.51, 3.43, 3.42, 3.32])

73    3.60
0     2.40
58    3.47
22    3.20
12    3.08
70    3.59
10    3.02
18    3.17
4     2.83
65    3.52
40    3.37
47    3.40
35    3.31
81    3.73
55    3.47
54    3.44
33    3.29
Name: GPA, dtype: float64